#!/usr/bin/env python3
"""One-off: translate case study pages to English (product framing)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

VD = ROOT / "src/pages/CaseVD.tsx"
AERONIS = ROOT / "src/pages/CaseAeronis.tsx"
ROOM = ROOT / "src/pages/CaseRoomCost.tsx"

VD_REPL = {
    "КЕЙС": "CASE",
    "Когда мастер\n              <br />\n              становится <span": "When craft\n              <br />\n              becomes <span",
    "брендом": "a brand",
    "Сайт, который превратил\n              <br />\n              частного мастера\n              <br />в ощущение": "A perception system that moved\n              <br />\n              a private manufacturer\n              <br />toward",
    "премиального бренда": "premium product logic",
    "Не про мебель.": "Not a furniture catalog.",
    "Про восприятие, уровень и решение клиента.": "About perception, level, and client decision architecture.",
    "Главный экран проекта VD": "VD product interface — hero",
    "Контекст": "Context",
    "Отправная точка": "Starting point",
    "Клиент": "Client",
    "Клиент — владелец частного производства корпусной мебели.": "Owner of a custom cabinet furniture manufacturer.",
    "Опыт": "Experience",
    "Более 10 лет опыта.": "10+ years of manufacturing craft.",
    "Проблема восприятия": "Perception gap",
    "Но воспринимался как «мастер»,": "Read by the market as a skilled maker,",
    "а не как бренд.": "not as a brand.",
    "Производство корпусной мебели по дизайн-проектам": "VD production environment",
    "Проблема": "Problem",
    "Не было сайта.": "No coherent product narrative.",
    "Не было системы подачи.": "No perception system.",
    "Не было ощущения уровня.": "No premium signal.",
    "Были заказы — но не те клиенты.": "Demand existed—but not from the right segment.",
    "Был <strong>сильный продукт</strong>.\n          <br />\n          Но его <strong>не видели</strong>.": "A <strong>strong product</strong> the market <strong>could not read</strong> at the right level.",
    "Задача": "Product goal",
    "Перевести восприятие:": "Shift perception:",
    "из «делает мебель»": "from “makes furniture”",
    "«создаёт продукт уровня премиум»": "“defines premium product experience”",
    "Решение": "System design",
    "— Смысловая архитектура бренда — фундамент": "— Brand meaning architecture as foundation",
    "— Позиционирование": "— Positioning layer",
    "— Визуальная система": "— Visual system",
    "— Лендинг как сценарий внимания": "— Attention scenario as product surface",
    "Фрагмент системы преимуществ и подачи проекта VD": "VD value system interface",
    "Процесс": "Process",
    "Не дизайн ради дизайна.": "Logic before surface.",
    "Сначала логика.": "Meaning first.",
    "Потом структура.": "Structure second.",
    "И только затем визуал.": "Interface last.",
    "Визуал": "Interface system",
    "Новая система в действии": "Product surface in action",
    "Фрагмент портфолио с жилыми интерьерами": "Living interior portfolio module",
    "Фрагмент портфолио с кухонными проектами": "Kitchen portfolio module",
    "Блок для дизайнеров и система партнерской подачи": "Designer partner workflow module",
    "Результат": "Outcome",
    "Из «мастера» — в <span className=\"font-medium text-[#ff7a4d]\">системный бренд</span> с характером.": "From workshop signal to <span className=\"font-medium text-[#ff7a4d]\">systemic brand</span> with weight.",
    "Из сайта — в <span className=\"font-medium text-white\">инструмент восприятия.</span>": "From static presence to <span className=\"font-medium text-white\">perception infrastructure.</span>",
    "Сайт перестал рассказывать.": "The interface stopped explaining.",
    "Он начал продавать уровень.": "It started selling level.",
    "Это не про сайт.": "This is not about a page.",
    "Это про то, как меняется восприятие,": "It is about how perception shifts",
    "когда у бренда появляется система.": "when a brand gains a system.",
    "Explore more product cases": "Back to cases",
    "Собрать такой же уровень для вашего проекта": "Back to cases",
    "Обсудить проект": "Connect",
}

AERONIS_REPL = {
    "КЕЙС": "CASE",
    "Инструмент, который избавляет\n              <br />\n              от бесконечного поиска билетов": "A product that ends\n              <br />\n              endless flight search",
    "Сервис, который сам отслеживает маршруты\n              <br />и показывает": "A system that monitors routes\n              <br />and surfaces",
    "лучший вариант": "one best option",
    "Не про авиацию.": "Not about aviation.",
    "Про время, нервы и выбор.": "About time, cognitive load, and decision compression.",
    "Интерфейс Aeronis: главный экран": "Aeronis interface — main screen",
    "Контекст": "Context",
    "Клиент": "User",
    "Пользователь, который устал искать билеты вручную.": "A traveler exhausted by manual comparison across tabs.",
    "Проблема": "Problem",
    "— открывает десятки вкладок": "— opens dozens of tabs",
    "— сравнивает цены": "— compares prices manually",
    "— не уверен, что нашёл лучший вариант": "— never confident the best option was found",
    "Нет системы. Только ручной поиск.": "No system. Only manual search.",
    "Задача": "Product goal",
    "Сделать инструмент, который:": "Build a product that:",
    "— сам отслеживает маршруты": "— monitors routes autonomously",
    "— предлагает лучший вариант": "— ranks one recommendation",
    "— упрощает выбор до одного действия": "— collapses choice to one action",
    "Решение": "System design",
    "Система анализирует направления и показывает рекомендации на основе табло.": "The system analyzes routes and recommends from live board data.",
    "Лента рекомендаций и табло направлений": "Recommendation feed and route board",
    "Фрагмент табло с направлениями": "Route board detail",
    "Как это работает": "How it works",
    "Пользователь задаёт маршрут и параметры.": "The user sets route intent and constraints once.",
    "Поиск перелёта в одну сторону": "One-way search flow",
    "Поиск перелёта туда и обратно": "Round-trip search flow",
    "Результат": "Outcome",
    "Сервис показывает готовый вариант перелёта.": "The product returns a ready-to-book itinerary.",
    "Готовый вариант перелёта": "Ready-to-book flight option",
    "Итог — готовое решение, без поиска вручную.": "Outcome: a decision, not a search session.",
    "Он перестаёт искать.": "Search ends.",
    "Сервис делает это за него.": "The system decides.",
    "Обсудить проект": "Connect",
}

ROOM_REPL = {
    "КЕЙС": "CASE",
    "Расчёт ремонта\n              <br />\n              без таблиц и догадок": "Renovation estimate\n              <br />\n              without spreadsheets",
    "Мобильное приложение, которое помогает быстро посчитать площадь помещения и предварительный\n              бюджет работ": "A mobile product for fast room-area and budget estimation before renovation starts",
    "Не про сложные сметы.": "Not about complex quotes.",
    "Про ясность до начала ремонта.": "About clarity before work begins.",
    "RoomCost — презентационный баннер": "RoomCost — product banner",
    "Контекст": "Context",
    "Знакомая ситуация:": "A familiar loop:",
    "нужно понять, во сколько примерно обойдётся ремонт": "estimate renovation cost early",
    "но для этого приходится считать вручную": "but everything is manual",
    "держать всё в голове или в заметках": "numbers live in notes and memory",
    "перепроверять цифры": "rechecking breaks trust",
    "Если помещений несколько —": "Multiple rooms multiply error risk.",
    "ошибиться становится ещё проще": "",
    "Проблема": "Problem",
    "Человеку нужен быстрый ориентир по стоимости": "People need a fast cost orientation",
    "Но нет простого инструмента": "No simple product path",
    "чтобы из размеров сразу получить понятную цифру": "from dimensions to a clear number",
    "Решение": "System design",
    "Пользователь вводит размеры помещения": "User enters room dimensions",
    "и стоимость за м²": "and cost per m²",
    "Приложение автоматически считает площади": "The system calculates areas",
    "и показывает итоговую стоимость": "and returns total cost",
    "RoomCost — ввод размеров и стоимости": "RoomCost — dimension input",
    "Как это работает": "How it works",
    "Ввод размеров": "Dimensions in",
    "расчёт площадей": "area computed",
    "учёт проёмов": "openings deducted",
    "итоговая сумма": "total out",
    "RoomCost — форма ввода размеров (светлая)": "RoomCost — input form (light)",
    "RoomCost — учёт проёмов": "RoomCost — openings module",
    "Расчёт становится быстрым и понятным": "Estimation becomes fast and legible",
    "Без формул": "No formulas exposed",
    "без таблиц": "No spreadsheets",
    "без повторных пересчётов": "No repeated recalculation loops",
    "RoomCost — итоговая стоимость": "RoomCost — total result",
    "Финал": "Outcome",
    "RoomCost превращает первый расчет ремонта в четкое понимание бюджета": "RoomCost turns the first renovation estimate into budget clarity",
    "Собрать такой же инструмент для вашего проекта": "Back to cases",
    "Обсудить проект": "Connect",
}

def apply(path: Path, mapping: dict) -> None:
    text = path.read_text(encoding="utf-8")
    for src, dst in sorted(mapping.items(), key=lambda x: -len(x[0])):
        text = text.replace(src, dst)
    path.write_text(text, encoding="utf-8")

if __name__ == "__main__":
    apply(VD, VD_REPL)
    apply(AERONIS, AERONIS_REPL)
    apply(ROOM, ROOM_REPL)
    print("Translated case pages.")
